<?php
    //caminho do servidor...
    $index = "http://localhost/UTD/blog-utd";
    //raiz do sistema...
    $raiz_dir   = $_SERVER['DOCUMENT_ROOT']."/UTD/blog-utd";
    //urls de css...
    $app_css = $index."/static/css/app.css";
    $bootstrap_css = $index."/static/css/bootstrap.css";
    $bootstrap_responsive_css = $index."/static/css/bootstrap-responsive.min.css";
    $font_awesome = $index."/static/css/font-awesome.min.css";
    //urls das imagens
    $images = $index."/static/img/";
    //urls de js...
    $bootstrap_js = $index."/static/js/bootstrap.js";
    $jQuery = $index."/static/js/jquery.js";
    //paginas do site
    $fale_conosco = $index."/views/fale-conosco.php";
    $produtos = $index."/views/produtos.php";
    $localizacao = $index."/views/localizacao.php";
    $galeria = $index."/views/galeria.php";
    //paginas da area administrativa
    $new_user   = $index."/admin/usuario.php?pg=newuser";
    $list_user  = $index."/admin/usuario.php?pg=listuser";
    $alt_user   = $index."/admin/usuario.php?pg=altuser";
    $new_cat    = $index."/admin/post.php?pg=newcat";
    $list_cat   = $index."/admin/post.php?pg=listcat";
    $alt_cat    = $index."/admin/post.php?pg=altcat";
    $new_post   = $index."/admin/post.php?pg=newpost";
    $list_post  = $index."/admin/post.php?pg=listpost";
    $alt_post   = $index."/admin/post.php?pg=altpost";
    $new_midia  = $index."/admin/midia.php?pg=newmidia";
    $list_midia = $index."/admin/midia.php?pg=listmidia";
    $coments    = $index."/admin/coments.php";